# Setup
title:        Hello World!
tagline:      Portfolio personnel
baseurl:      ""
paginate:     9
paginate_path:  "/blog/page:num/"
permalink:  pretty

# About/contact
author:
  name:       Jacquiot Christopher
  url:        https://www.linkedin.com/in/christopher-jacquiot-6291a5b2/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-menus

#Others
markdown: kramdown
