# Setup
title:        Hello World!
tagline:      Portfolio personnel
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jacquiot Christopher
  url:        https://www.linkedin.com/in/christopher-jacquiot-6291a5b2/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
